-- Phase 9.3 — AI background nudges
--
-- Stores ranked, dismissible nudges generated by the scheduled
-- generate-nudges-* Netlify functions. Each nudge is scoped to a
-- (workspace, user) and only shown to that user. RLS enforces that.
--
-- Nudges aren't immortal: they expire after ~24h so we don't stack
-- stale insights on the home page. The runner re-evaluates each
-- slot and inserts fresh rows.

create table if not exists ai_nudges (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  -- High-level family for grouping / future analytics. The runner can
  -- emit any short string; we accept anything to keep prompt design
  -- flexible.
  kind text not null,
  severity text not null
    check (severity in ('low', 'medium', 'high', 'urgent'))
    default 'medium',
  title text not null,
  body text,
  -- Optional structured payload (e.g. task_ids the nudge points at).
  payload jsonb,
  status text not null
    check (status in ('active', 'dismissed', 'expired'))
    default 'active',
  -- Which slot of which day produced this — useful for de-duping
  -- digests + activity analytics later. Format: 'YYYY-MM-DD:morning'
  slot text,
  created_at timestamptz not null default now(),
  dismissed_at timestamptz,
  expires_at timestamptz not null default (now() + interval '24 hours')
);

create index if not exists ai_nudges_user_active_idx
  on ai_nudges(user_id, status, expires_at desc);

alter table ai_nudges enable row level security;

drop policy if exists "users see own nudges" on ai_nudges;
create policy "users see own nudges" on ai_nudges
  for select using (user_id = auth.uid());

-- Users can dismiss their own nudges (UPDATE status / dismissed_at).
drop policy if exists "users update own nudges" on ai_nudges;
create policy "users update own nudges" on ai_nudges
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Insert is service-only (the scheduled function uses the service
-- role key, which bypasses RLS). We DON'T grant insert to authenticated
-- users so the table stays trustworthy.
